name = "Hospitalplanning"
uuid = "9130f150-e99a-11e9-06fb-a56735eead42"
authors = ["Henrik Bøgedal Breddam"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
